### PR TITLE
fix: Allow Windows installation without elevating privileges

### PR DESCRIPTION
**Pull request by c-sami**
**Changelog**

Lowered User Account Control (UAC) required level in Windows version.

**Bugfixes**

Allows installation and usage if user doesn't have admin rights. #284

**Enhancements**

-

**Notes**

About different levels: https://docs.microsoft.com/en-us/cpp/build/reference/manifestuac-embeds-uac-information-in-manifest?view=msvc-170#remarks

If user belongs to Administrators group, installer will pop up an UAC window for privilege elevation, installation proceeds and application works.

If user does not belong to Administrators group but uses different account (eg. adm-user) for administrative tasks, installer will pop up the UAC window for privilege elevation, user needs to use adm-user credentials and application gets installed under adm-user's profile. When user starts the application, the UAC prompt will show up, user needs to provide adm-user credentials and application will start. Sessions doesn't work because for example user's non-elevated command prompt doesn't have access to adm-user's profile where session data is stored. So in that example user's AWS session data is under `C:\Users\user\.aws\` and as Leapp is running elevated, it has stored credentials under `C:\Users\adm-user\.aws\`.

I have built fixed versions and used them with "aws iam user" and "aws single sign-on" sessions since at least Leapp v0.8.0 and haven't had any problems so far.

I need help with testing this in different scenarios, eg. with user that has ability to elevate into admin without different credentials and with different cloud profiles.

### CODE REVIEW

**Comment by pethron** [comment]
It seems ok, but we'll try to test on different scenarios before merging; thanks for your contribution!

**Comment by ericvilla** [comment]
Hello @c-sami! We have done some tests on our side.
We set up a VMWare Windows 10 x64 virtual machine with an admin user and a non-admin one.
We've downloaded the application for both users and the setup wizard does not show the UAC modal. This sounds a little bit strange, as in your case a UAC window is displayed for privilege escalation.

**Comment by ericvilla** [comment]
We analyzed [this](https://docs.microsoft.com/en-us/previous-versions/bb756929(v=msdn.10)) Microsoft documentation. Can you figure out your use case from the following tables?

Screenshot 2022-08-05 at 10 06 38

**Comment by ericvilla** [comment]
We tested Leapp with the `requestedExecutionLevel` option set to asInvoker. It works for the following type of user:

- user who is part of the Administrators group;
- standard user who is not part of the Administrators group.

Both the setup and application executables do not prompt for admin credentials (UAC).
We verified that the application is correctly writing/reading to/from the file system and keychain. Another critical point was the DPApi addon, used to encrypt Azure msal_token_cache.bin file used to access Azure-based Subscriptions in a specific Azure Tenant.

For these reasons, we consider this PR as mergeable to the master branch.

Thank you very much @c-sami for your contribution! We really appreciate it.

**Comment by c-sami** [comment]
Finally found out what was the cause. From the same document:
image

I wasn't in 'Backup Operator', but running `whoami /groups` in Command Prompt revealed that I (and all Domain Users) belong to group `BUILTIN\Network Configuration Operators`. It might be needed due to VPN.

When I removed Domain Users (that includes myself) from that group and rebooted, I didn't get UAC prompt during installation or using Leapp.
Added Domain Users back and rebooted and UAC prompt was back.

Colleague tested and had same results, but also found out that installers and Leapp's UAC prompt accepts also normal user's credentials (the one's that you are logged in). That caused that UAC prompt still popped up every time Leapp was started.

So changing `requestedExecutionLevel` was good to change. I hope that if someone similar corporate active directory domain user tried Leapp and thought that it didn't work or couldn't install it, tries installing and using Leapp again.

**Pull request merged**
