### PR TITLE
feat: add support for aws azuread federation

### LINKED ISSUE #160: Azure AD Login to AWS with AWS SAML
**Is your feature request related to a problem? Please describe.**
My company uses AzureAD to authenticate into AWS using SAML Authentication (Not AWS SSO). It does not appear that Leapp currently supports this. This is accomplished by logging into AWS using a AWS SAML URL like https://signin.aws.amazon.com/saml/AWS-ACCOUNT-1

**Describe the solution you'd like**
Would like to accomplish the login flow with Leapp.

**Describe alternatives you've considered**
We currently use https://github.com/sportradar/aws-azure-login for this and when it comes to CI/CD to access AWS and it works well, however it has proven to be a barrier for our developers.

### PR DESCRIPTION
**Pull request by mholttech**
This adds support for using AzureAD to Federate into AWS. Fixes #160.

**Changelog**

* Adds support for AzureAD Federation of AWS IAM Roles

### CODE REVIEW

**Comment by mholttech** [comment]
> This pull request **introduces 1 alert** when merging [0a7ca2a](https://github.com/Noovolari/leapp/commit/0a7ca2ac6b279a71c12145195a38168f92c06c89) into [00b89d7](https://github.com/Noovolari/leapp/commit/00b89d74ec7439cd172be45f6c7e1e47201e7a8b) - [view on LGTM.com](https://lgtm.com/projects/g/Noovolari/leapp/rev/pr-7cb1d4b2aad1d131a6da96bfb8625a94a7d93378)
> 
> **new alerts:**
> 
> * 1 for Incomplete URL substring sanitization

The full URL when authenticating is https://login.microsoftonline.com/<azuread-tenant-id>/saml2

I'm not sure if this is something that can be wildcarded for or if this needs to be handled differently.

**Comment by ericvilla** [comment]
Hi @mholttech, looking at [this](https://github.com/Noovolari/leapp/blob/7c117041b12292f378a84e5453fe56ea22fb6114/src/app/services/session/aws/methods/aws-iam-role-federated.service.ts#L153) implementation, it seems the filters you've added fit how the needAuthentication method works. Basically, it is an addition to the current logic and does not interfere with it.
Thank you very much for the effort and we'll add the feature in the next release.

**Comment by pethron** [comment]
I think the filter works but to further scope down I'd make a try with "https://login.microsoftonline.com/*/saml2"

**Comment by mholttech** [comment]
I just tried that with my dev build, unfortunately that appears to break the SAML Authentication

**Comment by ericvilla** [comment]
Hi @mholttech!

I've set up a federation between an AzureAD SAML Application and an AWS IAM Identity Provider. 

The solution works with your implementation, but it shows the login window every time you click to activate the session. The reason behind this behavior is that `details.url.indexOf('login.microsoftonline.com') !== -1` filter is too open. 

The very first call to _login.microsoftonline.com_ host has the following template: _https://login.microsoftonline.com/<azuread-tenant-id>/oauth2/authorize_

The condition now is 
`if (details.url.indexOf('login.microsoftonline.com') !== -1 && details.url.indexOf('/oauth2/authorize') !== -1) { ... }`

Using this condition, Leapp does not show the login windows if you're already logged in.

**Comment by mholttech** [comment]
Hey @ericvilla, Thanks for the feedback. I'm updating the filter on my local build to validate on my end and then I'll update the PR

**Comment by mholttech** [comment]
@ericvilla It looks good to me. Works as expected and no longer seeing the popup during credential refresh

**Pull request merged**
