### PR TITLE
feat: added Copy Web Console URL action

### LINKED ISSUE #296: Allow copying the URL for "Open Web Console"
**Is your feature request related to a problem? Please describe.**
Leapp automatically opens the web console in the default browser. This prevents me from using firefox containers which in turn means I can only have one session active at a time in the browser.

**Describe the solution you'd like**
I'd like to be able to copy the URL so that I can choose which firefox container it's opened in

**Describe alternatives you've considered**
I'm not aware of any work arouns.

### PR DESCRIPTION
**Pull request by c-sami**
**Changelog**

Added "Copy Web Console URL" action in session's copy-context menu.

**Bugfixes**

**Enhancements**

Closes #296.

**Notes**

Is this needed also in CLI?
No new tests as `openWebConsole - generates a valid aws url to log` covers it.

Any comments, enhancements, proposals, fixes are very welcome.

### CODE REVIEW

**Comment by pethron** [comment]
Would be awesome to open the browser from the CLI either. In general we're trying to keep the correspondence of actions between the gui and cli.

**Comment by c-sami** [comment]
Agree. I'll have a check on CLI also.

**Comment by c-sami** [comment]
Now that I got into it, it was easy to implement. But now it wonders if CLI command `session open-web-console` should be changed into `session web-console open|print`. I made a question about it in original issue: https://github.com/Noovolari/leapp/issues/296#issuecomment-1196820991

**Comment by pethron** [comment]
I think the two separate commands `open | print` would be better, as you suggested in the original issue.

**Comment by c-sami** [comment]
Great! I'll create documentation and tests for it and test it also in linux and mac tomorrow before pushing the CLI changes.

**Comment by c-sami** [comment]
Added CLI action and Jest-tests for it.
Ran core, cli and desktop-app tests and all succeeded.
Tested with AWS SSO in Windows 10, Ubuntu 22.04 and macOS 12.4 Monterey.
I feel this is ready for a review.

**Comment by pethron** [comment]
Great work, Sami! 🥇 I think @ericvilla can review this next week, and we can integrate everything in the next release

**Comment by rick-rtt** [comment]
Thanks for the excellent pull request! After review, we decided to add an optional flag `--print` to the `leapp session open-web-console` command instead of using a different command, everything else is perfect as it is! We are going to merge this to master and release it later today, so stay tuned! And thanks again!

**Comment by c-sami** [comment]
Glad to hear. It was 50/50 whether to use flag or create a new command and it is easy to change.

**Pull request merged**
