### PR TITLE
Add Github Actions npm build

### PR DESCRIPTION
**Pull request by gliptak**
https://github.com/gliptak/leapp/actions/runs/485718203

### CODE REVIEW

**Comment by ericvilla** [comment]
Hi @gliptak, thanks for taking the time and for your contribution and interest in Leapp project!  

I saw that - through the `npm run build` command - you're building the Angular solution inside a Ubuntu environment. 

Starting from Angular's /dist folder, we usually build the Electron solution; then - when we want to create a new release - we upload the results of the electron build as a new draft, to validate it. 

I'm just trying to understand if your expected behavior is to run an Angular build inside Ubuntu to build and test the application, or to create the application's artifacts. In the latter use case, I think you missed the electron part of the process.

Cheers!

**Comment by gliptak** [comment]
First target would be to run build/test for PRs and merges.

A follow-up could be automate your (multi-platform?) release process

**Comment by ericvilla** [comment]
Hi @gliptak, as described in the [v1.0.0 Project](https://github.com/Noovolari/leapp/projects/4), we're going to split the codebase in two: a Desktop Application and a Daemon. 

- The latter will contain the business-logic of Leapp, and expose it through an API (we're considering gRPC as a valid protocol for IPC communication).
- The Desktop Application will act as a pure front-end that invokes the Daemon that encapsulates all the core functionalities.

That said, I don't think this is the right moment to setup a CI/CD pipeline on a repository that - after the v1.0.0 release - will no more be supported. We can discuss about this topic together in view of v1.0.0 release, and any of your contributions are welcome!

Given that you explored this topic more in detail, what's your opinion about Travis CI and Circle CI to implement a CI/CD pipeline?

**Comment by gliptak** [comment]
@ericvilla Based on a quick review, external build services are constraining parallel builds, some requiring to login to see build logs and moving into a "credit" system for OSS projects,

https://www.appveyor.com/pricing/
https://travis-ci.com/account/plan?billingStep=1
https://circleci.com/pricing/index.html

As Github Actions extends OSs supported

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

and more and more Actions are published, it might be a preferable build tool.

**Comment by ericvilla** [comment]
Thank you @gliptak for your analysis! We never went into the detail of the pricing, and I think that's another important aspect that should be taken into account when deciding the right build technology.

**Pull request closed without merging**
