### PR TITLE
Feature/m1 support

### PR DESCRIPTION
**Pull request by nwouda**
**Changelog**

- Added native support for Apple M1 devices
- Bumped used NodeJS version to 16.14.1

**Enhancements**

- Added native support for Apple M1 devices

### CODE REVIEW

**Comment by andreacavagna01** [comment]
😍 will look at it tomorrow! Great job

**Comment by nwouda** [comment]
There's also an option to build a `universal` release. Haven't tested it, but it should provide a single executable that is compatible with both architectures.

**Comment by andreacavagna01** [comment]
have you tried to npm install? it breaks the code to me

**Comment by nwouda** [comment]
Yes, I've successfully built it for local use. It only fails when trying to sign the release because it points to credentials I don't have on my system. 

I'll do a clean build sometime soon to see if it still works. I could also try on a Windows and a Linux host to see if I get different results.

**Comment by nwouda** [comment]
@andreacavagna01 Could you share what is breaking for you? I have also had issues, but those were related to dependency resolving.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: Leapp@0.10.0
npm ERR! Found: @angular/compiler@13.2.7
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"~13.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"13.3.0" from @angular/compiler-cli@13.3.0
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"^13.2.1" from the root project
npm ERR!   peer @angular/compiler-cli@"^13.0.0 || ^13.3.0-rc.0" from @angular-devkit/build-angular@13.3.0
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"^13.2.2" from the root project
```

These happen both on the main branch as well as my branch. I decided to use `--force` to install anyway and that did not result in any other issues. Because it doesn't seem related to my change I didn't bother trying to fix it.

**Pull request merged**
