### PR TITLE
feat: add the option to select between Terminal and iTerm2 under MacOS [LEAP-288]

### LINKED ISSUE #176: Use different terminal App instead of Terminal App
The problem faced is that people are using alternative Terminal Application than the Default one, like [iTerm](https://iterm2.com/) for macOS.

Add the ability to use the terminal App preferred by the user and not the default one!

At the moment, Leapp opens the terminal with the following function:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L53

This function use:
- for MacOS it uses an Applescript:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L55
- for Windows the start command:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L59
- for Linux it uses this command:
https://github.com/Noovolari/leapp/blob/4b975c6bd043d9383bc3b80ddf9cdbe170b82afd/src/app/services/execute.service.ts#L61

This action is used in the SSM connect the action of Leapp and can be tested [following the documentation](https://docs.leapp.cloud/tutorials/aws/aws_ssm_connect/)

### PR DESCRIPTION
**Pull request by jgrumboe**
**Changelog**

There's now the possibility to select between MacOs Terminal or iTerm2 for opening an SSM session.
This resolves #176 .

image

### CODE REVIEW

**Comment by ericvilla** [comment]
Hi @jgrumboe, sorry for the late answer! Adding temp tokens to the credentials file as you did makes sense. That said, applying credentials to the credentials file is the same as activating a session in the "normal" flow. Imo, a first pragmatic solution is to enable ssm for a macOs iTerm2 shell only if the corresponding session is already active (by clicking it from the sessions list). We may need to investigate passing env variables further

**Comment by ericvilla** [comment]
@andreacavagna01, @pethron, @urz9999 what do you think about opening an SSM shell only if the corresponding Leapp Session is active? I think that - until we found a proper way to handle env vars for iTerm2 shell - this is a pragmatic yet clean solution to address the need.

**Comment by jgrumboe** [comment]
@ericvilla I found this one in the iTerm2 discussion group: https://groups.google.com/g/iterm2-discuss/c/WVaA9DW4dL8/m/TbfFkmO9BQAJ
The question is if we can also assume them every MacOS user is automatically using zsh?!

**Comment by gangofnuns** [comment]
Hi -- Just noticed this discussion.  Rather than a temp file, have you considered a named pipe?    A utility such as mktemp can help to obfuscate the path name.  You might then issue a command to the shell which opens the fifo and reads environment variables, etc., then closes the file and loads the env.   A little extra diligence with permissions can make it unlikely the fifo will ever write to disk (though not a guarantee).  You might also encrypt the data -- send it via keychain app, if it's only a few kb.  If people are using AWS (seems likely), one might send it via a user-predefined pathway on S3.   Just a few thoughts.

**Comment by andreacavagna01** [comment]
@gangofnuns thanks for your thoughts, we are still looking for a smooth way to implement this

**Comment by jgrumboe** [comment]
Just rebased.

**Comment by jgrumboe** [comment]
@ericvilla cool, means I can close this one safely, right?

**Comment by ericvilla** [comment]
@jgrumboe we had to adapt your PR - from which we took inspiration - to the new UX/UI. If you agree, I'm gonna close this PR without merging it, cause it is not compatible with the new UX/UI

**Comment by jgrumboe** [comment]
Totally fine 👍

**Comment by andreacavagna01** [comment]
I'm going to close this pull request since this has been implemented with v0.10.0

**Pull request closed without merging**
